/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'english' : IDL.Null,
});
export const Passage = IDL.Record({ 'text' : IDL.Text, 'language' : Language });
export const Session = IDL.Record({
  'result' : IDL.Record({ 'timeTaken' : IDL.Nat, 'accuracy' : IDL.Float64 }),
  'passage' : Passage,
});

export const idlService = IDL.Service({
  'getPassagesByLanguage' : IDL.Func([Language], [IDL.Vec(Passage)], ['query']),
  'recordSession' : IDL.Func([Session], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Language = IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null });
  const Passage = IDL.Record({ 'text' : IDL.Text, 'language' : Language });
  const Session = IDL.Record({
    'result' : IDL.Record({ 'timeTaken' : IDL.Nat, 'accuracy' : IDL.Float64 }),
    'passage' : Passage,
  });
  
  return IDL.Service({
    'getPassagesByLanguage' : IDL.Func(
        [Language],
        [IDL.Vec(Passage)],
        ['query'],
      ),
    'recordSession' : IDL.Func([Session], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };